tuono-labs/tuono

crates/tuono/Cargo.toml, crates/tuono/src/source_builder.rs, crates/tuono_lib/Cargo.toml, crates/tuono_lib/src/response.rs, crates/tuono_lib_macros/Cargo.toml, docs/tutorial.md, examples/tutorial/src/routes/index.tsx, examples/tutorial/src/routes/pokemons/GOAT.rs, packages/lazy-fn-vite-plugin/package.json, packages/tuono/package.json, packages/tuono/src/router/components/RouterProvider.tsx, packages/tuono/src/router/hooks/useListenBrowserUrlUpdates.tsx, packages/tuono/src/router/hooks/useRouterStore.tsx, packages/tuono/src/router/hooks/useServerSideProps.tsx, packages/tuono/src/router/types.ts, packages/tuono/src/router/utils/from-url-to-parsed-location.ts
This PR implement the redirect machinery.
=> Handle redirections

crates/tuono/Cargo.toml, crates/tuono/src/app.rs, crates/tuono/src/cli.rs, crates/tuono/src/route.rs, crates/tuono_lib/Cargo.toml, crates/tuono_lib_macros/Cargo.toml, packages/fs-router-vite-plugin/package.json, packages/lazy-fn-vite-plugin/package.json, packages/tuono/package.json
Correctl deploy the documentation website on AWS S3
This PR fixes the static output folder structure in order to correctly serve the HTML files through the AWS CDN
=> Update static build html structures

.github/workflows/ci-documentation.yml, .github/workflows/deploy-documentation.yml, apps/documentation/Cargo.toml, apps/documentation/package.json
=> Update documentation tuono version

packages/router/src/hooks/useRoute.spec.tsx, packages/router/src/hooks/useRoute.tsx
In order to correctly handle pathnames that might finish with a slash we first sanitize them by removing the final slash.
=> Sanitize client side pathnames

packages/tuono/src/ssr/index.tsx
This PR removes the following head tags that initially were hardcoded in the SSR output:
```
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
```
=> Remove default head meta tags

crates/tuono/Cargo.toml, crates/tuono/src/source_builder.rs, crates/tuono/src/watch.rs, crates/tuono_lib/Cargo.toml, crates/tuono_lib/src/request.rs, crates/tuono_lib/src/response.rs, crates/tuono_lib/src/server.rs, crates/tuono_lib_macros/Cargo.toml, packages/fs-router-vite-plugin/package.json, packages/lazy-fn-vite-plugin/package.json, packages/router/package.json, packages/tuono/package.json
This PR improve the logging shape
=> Add response time to SSR GET log

CODE_OF_CONDUCT.md, CONTRIBUTING.md, README.md, apps/documentation/src/components/hero/hero.tsx, apps/documentation/src/routes/documentation/contributing.mdx, apps/documentation/src/routes/documentation/getting-started.mdx, apps/documentation/src/routes/documentation/index.mdx, apps/documentation/src/routes/documentation/installation.mdx, apps/documentation/src/routes/index.tsx
=> Fix spelling

crates/tuono/Cargo.toml, crates/tuono_lib/Cargo.toml, crates/tuono_lib_macros/Cargo.toml, packages/fs-router-vite-plugin/package.json, packages/lazy-fn-vite-plugin/package.json, packages/router/package.json, packages/tuono/package.json
=> Update version to v0.10.2

crates/tuono/Cargo.toml, crates/tuono_lib/Cargo.toml, crates/tuono_lib_macros/Cargo.toml, examples/tutorial/src/routes/pokemons/[pokemon].tsx, package.json, packages/fs-router-vite-plugin/package.json, packages/lazy-fn-vite-plugin/package.json, packages/router/package.json, packages/tuono/package.json, packages/tuono/src/hydration/index.tsx, packages/tuono/src/index.ts, packages/tuono/src/ssr/index.tsx
=> Move to react-helmet-async

apps/documentation/Cargo.toml, apps/documentation/package.json, apps/documentation/src/components/navigation-buttons/index.ts, apps/documentation/src/components/navigation-buttons/navigation-buttons.tsx, apps/documentation/src/routes/documentation/cli.mdx, apps/documentation/src/routes/documentation/contributing.mdx, apps/documentation/src/routes/documentation/index.mdx, apps/documentation/src/routes/documentation/installation.mdx, apps/documentation/src/routes/documentation/routing/index.mdx, apps/documentation/src/routes/documentation/routing/intro.mdx, apps/documentation/src/routes/documentation/tutorial/api-fetching.mdx, apps/documentation/src/routes/documentation/tutorial/components.mdx, apps/documentation/src/routes/documentation/tutorial/conclusion.mdx, apps/documentation/src/routes/documentation/tutorial/development-setup.mdx, apps/documentation/src/routes/documentation/tutorial/dynamic-routes.mdx, apps/documentation/src/routes/documentation/tutorial/error-handling.mdx, apps/documentation/src/routes/documentation/tutorial/index.mdx, apps/documentation/src/routes/documentation/tutorial/production.mdx, apps/documentation/src/routes/documentation/tutorial/redirections.mdx, apps/documentation/src/routes/documentation/tutorial/seo.mdx, apps/documentation/src/routes/index.tsx
=> Update documentation navigation

crates/tuono/Cargo.toml, crates/tuono_lib/Cargo.toml, crates/tuono_lib_macros/Cargo.toml, packages/fs-router-vite-plugin/package.json, packages/fs-router-vite-plugin/src/generator.ts, packages/fs-router-vite-plugin/src/index.ts, packages/fs-router-vite-plugin/src/utils/is-default-exported.ts, packages/fs-router-vite-plugin/tests/generator/mdx/routes/index.tsx, packages/fs-router-vite-plugin/tests/generator/multi-level-root-dynamic/routes/about.tsx, packages/fs-router-vite-plugin/tests/generator/multi-level-root-dynamic/routes/index.tsx, packages/fs-router-vite-plugin/tests/generator/multi-level-root-dynamic/routes/posts/[post].tsx, packages/fs-router-vite-plugin/tests/generator/multi-level-root-dynamic/routes/posts/__root.tsx, packages/fs-router-vite-plugin/tests/generator/multi-level-root-dynamic/routes/posts/index.tsx, packages/fs-router-vite-plugin/tests/generator/multi-level-root-dynamic/routes/posts/my-post.tsx, packages/fs-router-vite-plugin/tests/generator/multi-level/routes/about.tsx, packages/fs-router-vite-plugin/tests/generator/multi-level/routes/index.tsx, packages/fs-router-vite-plugin/tests/generator/multi-level/routes/posts/my-post.tsx, packages/fs-router-vite-plugin/tests/generator/single-level/routes/about.tsx, packages/fs-router-vite-plugin/tests/generator/single-level/routes/index.tsx, packages/lazy-fn-vite-plugin/package.json, packages/router/package.json, packages/tuono/package.json
=> Prevent not exported routes error

packages/router/src/components/Link.tsx, packages/router/src/hooks/useRouter.tsx
=> Prevent scroll offset on page navigation

crates/tuono/Cargo.toml, crates/tuono_lib/Cargo.toml, crates/tuono_lib_macros/Cargo.toml, packages/fs-router-vite-plugin/package.json, packages/lazy-fn-vite-plugin/package.json, packages/router/package.json, packages/router/src/dynamic.tsx, packages/tuono/package.json
Strongly inspired by [this](https://dev.to/blankhq/preloading-blog-post-content-f8a) article
=> Improve route preloading

apps/documentation/Cargo.toml, apps/documentation/package.json
=> feat: update documentation version to v0.11.2

README.md, apps/documentation/src/components/sidebar/sidebar.tsx, apps/documentation/src/routes/documentation/index.mdx
=> Update getting started

crates/tuono_lib/src/catch_all.rs
=> Add log to catch_all routes

README.md
=> Fix tutorial link in README

.github/workflows/ci-documentation.yml, .github/workflows/deploy-documentation.yml, .github/workflows/typescript.yml, apps/documentation/package.json, package.json, packages/fs-router-vite-plugin/.prettierignore, pnpm-workspace.yaml
Close #95.
`apps/documentation` is now part of `pnpm` workspaces.
All relevant scripts have been added to the root `package.json`.
> [!NOTE]
> Later I'm going to improve format also on `json` and `yml` files
=> chore: add `apps/documentation` to `pnpm` workspaces

.github/workflows/release.yml, crates/tuono/Cargo.toml, crates/tuono_lib/Cargo.toml, crates/tuono_lib_macros/Cargo.toml, packages/fs-router-vite-plugin/package.json, packages/lazy-fn-vite-plugin/package.json, packages/router/package.json, packages/tuono/package.json
This is an experiement. The `cargo publish` script fails to build the project even though the `cargo build` correctly run. The problem is related to the module imports.
=> Fix failing release pipeline

.github/workflows/ci-documentation.yml, .github/workflows/deploy-documentation.yml, apps/documentation/Cargo.toml, apps/documentation/package.json
=> Update documentation tuono to v0.12.3

.github/actions/install-node-dependencies/action.yml, .github/workflows/ci-documentation.yml, .github/workflows/deploy-documentation.yml, .github/workflows/release.yml, .github/workflows/rust.yml, .github/workflows/spell-checking.yml, .github/workflows/typescript.yml, .gitignore, pnpm-lock.yaml
Close #97.
Basically all proposition of the issue should implemented here!
I have executed a `pnpm i --ignore-packages` in each example folder.
=> ci: create `install-node-dependencies` action

apps/documentation/src/components/sidebar/sidebar.tsx, apps/documentation/src/routes/documentation/application-state.mdx, apps/documentation/src/routes/documentation/tutorial/api-fetching.mdx, crates/tuono/Cargo.toml, crates/tuono/src/app.rs, crates/tuono/src/source_builder.rs, crates/tuono_lib/Cargo.toml, crates/tuono_lib/src/server.rs, crates/tuono_lib/src/vite_reverse_proxy.rs, crates/tuono_lib_macros/Cargo.toml, crates/tuono_lib_macros/src/handler.rs, examples/tutorial/Cargo.toml, examples/tutorial/src/main.rs, packages/fs-router-vite-plugin/package.json, packages/lazy-fn-vite-plugin/package.json, packages/router/package.json, packages/tuono/package.json
So far the project allow the user to just perform http connection from the server side handlers. This is the first step to allow the users to define they own state (db connections, graphql, etc...).
=> Add support for custom global state

apps/documentation/src/routes/documentation/tutorial/dynamic-routes.mdx, apps/documentation/src/routes/documentation/tutorial/error-handling.mdx, crates/tuono/Cargo.toml, crates/tuono_lib/Cargo.toml, crates/tuono_lib/src/lib.rs, crates/tuono_lib_macros/Cargo.toml, crates/tuono_lib_macros/src/handler.rs, examples/tutorial/src/routes/index.rs, examples/tutorial/src/routes/pokemons/[pokemon].rs, packages/fs-router-vite-plugin/package.json, packages/lazy-fn-vite-plugin/package.json, packages/router/package.json, packages/tuono/package.json
In the previous feature I mixed two values in the `tuono_lib::handler` macro. With this PR I fixed it and I remove the re-exported `reqwest` crate since it has been removed
=> Fix tuono_lib_macro crate

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/feature_request.yml, .github/pull_request_template.md, .github/workflows/repo-root-ci.yml, .prettierignore, .prettierrc, CODE_OF_CONDUCT.md, CONTRIBUTING.md, package.json, renovate.json, tsconfig.json, turbo.json
Close #108.
I had to add another GitHub Actions workflow since this check doesn't apply strictly apply to `typescript` or `rust` codebases.
=> ci: add format check on repository root

crates/tuono/Cargo.toml, crates/tuono/src/app.rs, crates/tuono/src/route.rs, crates/tuono/src/source_builder.rs, crates/tuono_lib/Cargo.toml, crates/tuono_lib/src/lib.rs, crates/tuono_lib_macros/Cargo.toml, crates/tuono_lib_macros/src/api.rs, crates/tuono_lib_macros/src/handler.rs, crates/tuono_lib_macros/src/lib.rs, crates/tuono_lib_macros/src/utils.rs, examples/tuono/src/routes/api/health_check.rs, packages/fs-router-vite-plugin/package.json, packages/lazy-fn-vite-plugin/package.json, packages/router/package.json, packages/tuono/package.json
This PR adds the support to the `api/` folder in which the user can define any API endpoint that doesn't return any server side rendered HTML.
=> Add support for `api/` folder

crates/tuono/Cargo.toml, crates/tuono_lib/Cargo.toml, crates/tuono_lib_macros/Cargo.toml, crates/tuono_lib_macros/src/utils.rs, packages/fs-router-vite-plugin/package.json, packages/lazy-fn-vite-plugin/package.json, packages/router/package.json, packages/tuono/package.json
This PR fixes https://github.com/Valerioageno/tuono/issues/170
=> Fix optional application state parameters

renovate.json
Set renovate schedule to `every 2 weeks on monday` to reduce PR frequency.
=> chore(renovate): enable schedule

CONTRIBUTING.md, README.md, apps/documentation/src/components/edit-page/edit-page.tsx, apps/documentation/src/components/navbar/actions.tsx, apps/documentation/src/routes/documentation/index.mdx, examples/tuono-app/src/routes/index.tsx, packages/fs-router-vite-plugin/README.md, packages/lazy-fn-vite-plugin/README.md, packages/router/README.md
=> feat: update docs and readme repo links

crates/tuono/src/scaffold_project.rs
=> feat: update tuono new repository reference

crates/tuono/Cargo.toml, crates/tuono_lib/Cargo.toml, crates/tuono_lib_macros/Cargo.toml, packages/fs-router-vite-plugin/package.json, packages/lazy-fn-vite-plugin/package.json, packages/router/package.json, packages/tuono/package.json
=> feat: update version to v0.15.0

packages/router/src/components/RouterProvider.tsx, packages/router/src/route.ts, packages/router/src/router.ts
Followup to #147.
Remove unused code from `npm` `tuono-router` package.
=> refactor(packages/router): removed unused code

apps/documentation/src/routes/documentation/contributing/index.mdx
=> chore: update contributing documentation

crates/tuono/tests/cli_tests.rs, crates/tuono/tests/utils.rs
=> test: add integration tests for api/ build

apps/documentation/src/components/sidebar/sidebar.tsx, apps/documentation/src/routes/documentation/routing/defining-routes.mdx
=> docs: fill defining-routes page

.github/workflows/deploy-documentation.yml, apps/documentation/package.json, apps/documentation/tuono.config.ts, pnpm-lock.yaml
=> docs: update tuono to 0.16 and add mdx support

crates/tuono/src/lib.rs, crates/tuono_lib/src/lib.rs, crates/tuono_lib_macros/src/lib.rs
close https://github.com/tuono-labs/tuono/issues/195
added short description and website link for crates documentation
=> docs: added website link to creates documentation

.github/workflows/ci-documentation.yml, .github/workflows/deploy-documentation.yml, apps/documentation/Cargo.toml, apps/documentation/package.json, pnpm-lock.yaml
Debugging failing documentation CI
=> docs: update tuono

crates/tuono/Cargo.toml, crates/tuono/src/scaffold_project.rs, crates/tuono_lib/Cargo.toml, crates/tuono_lib_macros/Cargo.toml, packages/tuono-fs-router-vite-plugin/package.json, packages/tuono-lazy-fn-vite-plugin/package.json, packages/tuono-router/package.json, packages/tuono/package.json
Close: https://github.com/tuono-labs/tuono/issues/282
=> Load template by tag

packages/tuono-fs-router-vite-plugin/src/generator.ts, packages/tuono-fs-router-vite-plugin/tests/generator/catch_all/routeTree.expected.ts
Close: https://github.com/tuono-labs/tuono/issues/242
=> fix: catch-all server side handler

scripts/dev.sh
This PR just fixes the `scripts/dev.sh` script that was useless with the previous setup
=> fix: dev script

.github/labeler.yml, .github/workflows/pr-labeler.yml
=> chore: add PR labeler

apps/documentation/src/routes/documentation/hooks/use-router.mdx, packages/tuono-router/src/hooks/useRouter.tsx
Fixes #338 and references https://github.com/tuono-labs/tuono/pull/325#issuecomment-2587714884
=> chore: refine useRouter return type and update docs

renovate.json
=> chore(renovate): fix schedule

packages/tuono/src/config/types.ts
Unblocks tailwindcss via vite plugin, see [discord thread](https://discordapp.com/channels/1307411506735874208/1328741117872701602).
=> fix(packages/tuono):  config - correct `vite.plugins` type

apps/documentation/src/routes/documentation/configuration.mdx
@marcalexiei @avj2352 I removed this sentence since I think that for the user perspective, that does not know the codebase, it does not make much sense!
=> docs(configuration): remove unclear doc

crates/tuono/Cargo.toml, crates/tuono_lib/Cargo.toml, crates/tuono_lib_macros/Cargo.toml, packages/tuono-fs-router-vite-plugin/package.json, packages/tuono-router/package.json, packages/tuono/package.json
=> chore: bump version to v0.17.1

crates/tuono/Cargo.toml, crates/tuono_lib/Cargo.toml, crates/tuono_lib_macros/Cargo.toml, packages/tuono-fs-router-vite-plugin/package.json, packages/tuono-router/package.json, packages/tuono/package.json
=> fix: revert "chore: bump version to v0.17.1"

.github/workflows/repo-root-ci.yml, .github/workflows/rust.yml, .github/workflows/typescript.yml
Close #336 (definitely)
[To a complete breakthrough of the problem check the readme in this repository](https://github.com/marcalexiei/github-actions-multiple-ci-workflow-playground)
=> ci: add unique names on `ci_ok` jobs

crates/tuono/Cargo.toml, crates/tuono_lib/Cargo.toml, crates/tuono_lib_macros/Cargo.toml, packages/tuono-fs-router-vite-plugin/package.json, packages/tuono-router/package.json, packages/tuono/package.json
=> chore: bump version to v0.17.3

apps/documentation/package.json, packages/tuono-router/package.json, packages/tuono/package.json, pnpm-lock.yaml
Supersedes #376 
(same as #376 + `pnpm dedupe`)
=> chore(deps): update dependency @types/react to v19.0.7

crates/tuono/Cargo.toml, crates/tuono/src/app.rs, crates/tuono/src/cli.rs, crates/tuono/src/mode.rs, crates/tuono/tests/cli_build.rs, crates/tuono_internal/src/config.rs
Closes: https://github.com/tuono-labs/tuono/issues/397
=> feat: load `config` in tuono CLI

README.md
=> refactor: streamline readme

crates/tuono_internal/src/config.rs, crates/tuono_lib/Cargo.toml, crates/tuono_lib/src/config.rs, crates/tuono_lib/src/lib.rs, crates/tuono_lib/src/payload.rs, crates/tuono_lib/src/server.rs, crates/tuono_lib/src/vite_reverse_proxy.rs, crates/tuono_lib/src/vite_websocket_proxy.rs, packages/tuono-router/src/types.ts, packages/tuono/src/shared/DevResources.tsx
Closes: https://github.com/tuono-labs/tuono/issues/396
This PR is the last piece of
- https://github.com/tuono-labs/tuono/issues/358
After this PR merge, I'm gonna release the feature with `v0.17.4`
I propose to update the documentation after the release.
=> feat: pass config from server to client

crates/tuono/Cargo.toml, crates/tuono_internal/Cargo.toml, crates/tuono_lib/Cargo.toml, crates/tuono_lib_macros/Cargo.toml, packages/tuono-fs-router-vite-plugin/package.json, packages/tuono-router/package.json, packages/tuono/package.json
=> chore: bump version 0.17.4

crates/tuono/src/cli.rs, crates/tuono/src/scaffold_project.rs
Fixes #262, and supersedes #292
=> feat(crates/tuono): add `--head` flag to download most recent template

.github/workflows/ci-documentation.yml, .github/workflows/deploy-documentation.yml, apps/documentation/Cargo.toml, apps/documentation/package.json, eslint.config.js, pnpm-lock.yaml
Looks like that documentation build hangs indefinitely:
Check last run in https://github.com/tuono-labs/tuono/actions/workflows/ci-documentation.yml?query=is%3Afailure
- E.g.: https://github.com/tuono-labs/tuono/actions/runs/12960686728/job/36154922153
- This was also reported by @jacobhq in https://github.com/tuono-labs/tuono/pull/394#issuecomment-2612957827
Let's see if updating to the last version fixes the issue.
=> docs: update tuono to 0.17.5

apps/documentation/src/components/MdxWrapper/MdxWrapper.tsx
=> fix(docs): content overflow

.github/workflows/pr-title-checker.yml
=> ci(pr-title-checker): test type is marked as invalid

apps/documentation/package.json, packages/tuono-router/package.json, packages/tuono/package.json, pnpm-lock.yaml
=> chore(deps): update dependency @types/react to v19.0.8

packages/tuono-router/package.json, packages/tuono-router/vite.config.ts, pnpm-lock.yaml
=> test(packages/tuono-router): replace `jsdom` with `happy-dom`

.github/pull_request_template.md, apps/documentation/src/routes/documentation/contributing/local-development.mdx, apps/documentation/src/routes/documentation/contributing/pull-requests.mdx
=> docs: add notes about pull request and validating changes

crates/tuono/Cargo.toml, crates/tuono_internal/Cargo.toml, crates/tuono_lib/Cargo.toml, crates/tuono_lib_macros/Cargo.toml, packages/tuono-fs-router-vite-plugin/package.json, packages/tuono-router/package.json, packages/tuono/package.json
=> chore: bump version to v0.17.6

.github/workflows/documentation-ci.yml, .github/workflows/documentation-deploy.yml, apps/documentation/Cargo.toml, apps/documentation/package.json, pnpm-lock.yaml
None
Releasing a new tuono version made the documentation fail CI hangs indefinitely again.
See #419
=> docs: update to tuono 0.17.6

apps/documentation/README.md, apps/documentation/src/components/Hero/Hero.tsx, apps/documentation/src/routes/documentation/cli.mdx, apps/documentation/src/routes/documentation/components/link.mdx, apps/documentation/src/routes/documentation/installation.mdx, apps/documentation/src/routes/documentation/routing/defining-routes.mdx, apps/documentation/src/routes/documentation/tutorial/api-fetching.mdx, apps/documentation/src/routes/documentation/tutorial/development-setup.mdx, apps/documentation/src/routes/documentation/tutorial/dynamic-routes.mdx, apps/documentation/src/routes/documentation/tutorial/index.mdx, apps/documentation/src/routes/documentation/tutorial/production.mdx, examples/README.md, examples/tuono-app/README.md, examples/tuono-tutorial/README.md, examples/with-mdx/README.md, examples/with-tailwind/README.md
Superseds
- #418
---
Blocked by
- #449
=> docs: use consistent snippet style across the codebase

apps/documentation/src/components/MdxProvider/MdxTitle/MdxTitle.tsx
Fixes part of #465. May help with #466.
Generate IDs for headings consisting only of code
=> docs: add headings containing only code to ToC

apps/documentation/src/components/MdxProvider/MdxTitle/MdxTitle.tsx
=> fix: heading order

apps/documentation/src/components/TableOfContents/TableOfContents.module.css, apps/documentation/src/components/TableOfContents/TableOfContents.tsx, apps/documentation/src/components/TableOfContents/getHeadings.ts, apps/documentation/src/routes/documentation/configuration.mdx
Fixes #465 
https://github.com/user-attachments/assets/83cd98a9-0eea-4ef0-ab0c-8cd65183ea54
=> docs: indent ToC based on heading levels

apps/documentation/src/components/Sidebar/sidebarElements.ts, apps/documentation/src/routes/documentation/server-utilities/response.mdx
=> docs: add Response enum page

apps/documentation/src/routes/documentation/routing/defining-routes.mdx
=> docs: add TuonoScript component mention

apps/documentation/src/routes/__layout.tsx, apps/documentation/src/routes/documentation/routing/defining-routes.mdx
Fixes None
- Fix a typo
- Add border to dark mode quotes for better readability
=> docs: fix quote blocks

apps/documentation/src/routes/documentation/routing/defining-routes.mdx
=> docs: fix typo

apps/documentation/src/routes/documentation/styles/css-modules.mdx
Fixes #459
add `/styles/css-modules` page
=> docs: add `/styles/css-modules` page

apps/documentation/src/routes/documentation/integrations/mdx.mdx, apps/documentation/src/routes/documentation/styles/tailwind-css.mdx
Fixes #458 
I created here the `MDX` page. I also fixed the `TailwindCSS` page to align with `MDX`
=> docs: add mdx page

apps/documentation/src/components/MdxProvider/MdxProvider.tsx, apps/documentation/src/components/PageWithTOC/PageWithTOC.tsx, apps/documentation/src/components/TableOfContents/TableOfContents.tsx, apps/documentation/src/routes/policies/privacy.mdx
=> docs: add privacy policy

crates/tuono/src/scaffold_project.rs, examples/tuono-app/Cargo.toml, examples/tuono-tutorial/Cargo.toml, examples/with-mdx/Cargo.toml
=> fix: with-tailwind template download

package.json, pnpm-lock.yaml, turbo.json
Superseds #496
- update the schema to use the file provided inside `node_modules`
- consider usage of [`outputLogs: "new-only"`](https://turbo.build/repo/docs/reference/configuration#outputlogs)
=> chore(deps): update dependency turbo to v2.4.0

crates/tuono_lib/Cargo.toml
=> chore: update ssr_rs to v0.8.1

crates/tuono/Cargo.toml, crates/tuono_internal/Cargo.toml, crates/tuono_lib/Cargo.toml, crates/tuono_lib_macros/Cargo.toml, packages/tuono-fs-router-vite-plugin/package.json, packages/tuono-router/package.json, packages/tuono/package.json
=> chore: bump version to v0.17.7

apps/documentation/Cargo.toml, apps/documentation/package.json, pnpm-lock.yaml
=> docs: update tuono version to v0.17.7

apps/documentation/src/routes/sitemap.xml.rs
Fixes #527
Exclude 404 page from sitemap.xml
=> docs(sitemap.xml): exclude 404 page

apps/documentation/src/components/Sidebar/sidebarElements.ts, apps/documentation/src/routes/documentation/routing/api-routes.mdx
=> docs: add API routes page

apps/documentation/src/routes/documentation/application-state.mdx, apps/documentation/src/routes/documentation/cli.mdx, apps/documentation/src/routes/documentation/tutorial/index.mdx, apps/documentation/src/routes/index.mdx
Fixes None
- Fix documentation broken links
- Small text refinement on "Application state" page
=> docs: fix broken links

pnpm-lock.yaml
=> chore(pnpm):  dedupe dependencies

crates/tuono/Cargo.toml, crates/tuono_internal/Cargo.toml, crates/tuono_lib/Cargo.toml, crates/tuono_lib_macros/Cargo.toml, packages/tuono-fs-router-vite-plugin/package.json, packages/tuono-router/package.json, packages/tuono/package.json
=> chore: update version to v0.17.8

.editorconfig, crates/tuono/src/build.rs, crates/tuono/src/cli.rs, crates/tuono/src/lib.rs
Fixes #285
Show a spinner during `tuono build` process.
Moved build in a separate rust module to be consistent with watch module.
=> feat(crates/tuono): feat: add spinner to `tuono build`

package.json
Fixes my lack of attention in #568
Forgot to change `types` to `typecheck` inside root `package.json` during #568.
=> chore: correct missing `types` task reference

crates/tuono/src/source_builder.rs, crates/tuono/tests/cli_build.rs, crates/tuono_lib/tests/utils/utils.rs, crates/tuono_lib_macros/src/api.rs, crates/tuono_lib_macros/src/handler.rs
Fixes #562
Remove the double underscore from handler names and use true snake_case.
=> fix: use snake_case for handler names

.github/labeler.yml
Fixes None
Add dev tools to labeler config
=> chore: add devtools to labeler.yml

examples/with-tailwind/package.json, pnpm-lock.yaml
=> chore(examples/with-tailwind): update `tailwind` to v4.0.6

devtools/vite-config/package.json, packages/tuono-fs-router-vite-plugin/package.json, packages/tuono-router/package.json, packages/tuono/package.json, pnpm-lock.yaml
Fixes #567
Update vite to v6 and vitest v3
=> feat: update vite to v6 and vitest v3

crates/tuono/src/app.rs, crates/tuono/tests/cli_build.rs
Fixes #578 
Give the user more details, as this error can appear in a few situations.
=> feat: more detailed errors for `Failed to read tuono.config.ts`

package.json, pnpm-lock.yaml
=> chore(deps): update dependency prettier to v3.5.2

crates/tuono/src/app.rs, crates/tuono/src/route.rs, crates/tuono/tests/cli_build.rs, crates/tuono_lib/Cargo.toml, crates/tuono_lib/src/server.rs, crates/tuono_lib/src/vite_websocket_proxy.rs, crates/tuono_lib/tests/server_test.rs, crates/tuono_lib/tests/utils/catch_all.rs, crates/tuono_lib/tests/utils/dynamic_parameter.rs, crates/tuono_lib/tests/utils/mock_server.rs, crates/tuono_lib/tests/utils/mod.rs
Fixes None
Supersedes https://github.com/tuono-labs/tuono/pull/495
=> feat: update axum to v0.8.1

crates/tuono/Cargo.toml, crates/tuono_internal/Cargo.toml, crates/tuono_lib/Cargo.toml, crates/tuono_lib_macros/Cargo.toml, packages/tuono-fs-router-vite-plugin/package.json, packages/tuono-router/package.json, packages/tuono/package.json
=> chore: update version to v0.17.9

crates/tuono/src/route.rs
=> fix: build script for creation of parent directories

crates/tuono/Cargo.toml, crates/tuono_internal/Cargo.toml, crates/tuono_lib/Cargo.toml, crates/tuono_lib_macros/Cargo.toml, packages/tuono-fs-router-vite-plugin/package.json, packages/tuono-router/package.json, packages/tuono/package.json
=> chore: update version to v0.17.10

examples/tuono-app/.gitignore, examples/tuono-tutorial/.gitignore, examples/with-mdx/.gitignore, examples/with-tailwind/.gitignore
Fixes none
More specific gitignore to only ignore local env files, not `*.local`.
=> chore: more specific gitignores

package.json, pnpm-workspace.yaml
=> chore(deps): update pnpm to v10

packages/tuono-router/src/components/Link.spec.tsx, packages/tuono-router/src/components/Link.tsx, packages/tuono-router/src/components/Matches.tsx, packages/tuono-router/src/components/NotFound.tsx, packages/tuono-router/src/components/RouteMatch.tsx, packages/tuono-router/src/hooks/useRouter.ts, packages/tuono-router/src/index.ts
Fixes #259
- See linked issue
- Replaced some default export with named export (does not impact usage on user-side)
- `<NotFound />` 
- `<Link />`
=> refactor(packages/tuono-router): use named imports

eslint.config.js, package.json, packages/tuono-fs-router-vite-plugin/src/build-route-config.spec.ts, packages/tuono-fs-router-vite-plugin/src/has-parent-route.spec.ts, packages/tuono-fs-router-vite-plugin/src/sort-route-nodes.spec.ts, packages/tuono-router/src/components/Link.spec.tsx, packages/tuono-router/src/components/RouteMatch.spec.tsx, packages/tuono-router/src/hooks/useRoute.spec.ts, pnpm-lock.yaml
Fixes #296
Add `@vitest/eslint-plugin` to eslint configuration.
=> chore: add `@vitest/eslint-plugin`

crates/tuono/Cargo.toml, crates/tuono_internal/Cargo.toml, crates/tuono_lib/Cargo.toml, crates/tuono_lib_macros/Cargo.toml, packages/tuono-fs-router-vite-plugin/package.json, packages/tuono-router/package.json, packages/tuono/package.json
=> chore: update version to v0.18.0

package.json
=> chore(package): add missing `test` script to `check-packages`

crates/tuono/src/route.rs
=> fix: allow 'index' keyword in routes name

e2e/fixtures/base/src/routes/index.tsx, examples/tuono-app/src/routes/index.tsx, examples/tuono-tutorial/src/routes/index.tsx, examples/tuono-tutorial/src/routes/pokemons/[pokemon].tsx, packages/tuono/src/index.ts, packages/tuono/src/types.spec-d.ts, packages/tuono/src/types.ts, packages/tuono/vite.config.ts
Fixes #450
- rename `TuonoProps` in `TuonoRouteProps`
- refine type using a union to better describe his runtime behaviour 
(see https://github.com/tuono-labs/tuono/pull/646#discussion_r1996004374)
- added relevant unit test using [typecheck testing provided by Vite](https://vitest.dev/guide/testing-types.html)
=> feat(packages/tuono): improve `TuonoRouteProps` type

crates/tuono/Cargo.toml, crates/tuono_internal/Cargo.toml, crates/tuono_lib/Cargo.toml, crates/tuono_lib_macros/Cargo.toml, packages/tuono-fs-router-vite-plugin/package.json, packages/tuono-router/package.json, packages/tuono/package.json
=> chore: bump version to v0.19.0

crates/tuono/src/app.rs, crates/tuono/src/cli.rs, crates/tuono/src/commands/dev.rs, crates/tuono/src/main.rs, crates/tuono/src/source_builder.rs, crates/tuono/tests/cli_build.rs
Fixes None
This is the first PR for refactoring the `SourceBuilder`. 
This refactor is required because the upcoming needs of new feature managed by our watching CLI. Implementing the automatic typescript types require a more granular project management that is not scalable the way is developed right now.
Further PR are expected.
> Note: I'm focusing on collecting the sparse functions into a more meaningful struct (SourceBuilder). Bug might arise. On each PR I QA the output. At the end of the full refactoring a deep QA is required
=> refactor: source builder

pnpm-lock.yaml
=> chore: dedupe lockfile

crates/tuono_lib/Cargo.toml
=> chore: update ssr_rs to v0.8.2

crates/tuono/Cargo.toml, crates/tuono/src/app.rs, crates/tuono/src/cli.rs, crates/tuono/src/commands/build.rs, crates/tuono/src/commands/dev.rs, crates/tuono/src/commands/new.rs, crates/tuono/src/route.rs, crates/tuono/tests/cli_build.rs, crates/tuono/tests/utils/temp_tuono_project.rs, crates/tuono_internal/Cargo.toml, crates/tuono_internal/tests/utils.rs, crates/tuono_lib/Cargo.toml, crates/tuono_lib/src/catch_all.rs, crates/tuono_lib/src/env.rs, crates/tuono_lib/src/lib.rs, crates/tuono_lib/src/payload.rs, crates/tuono_lib/src/response.rs, crates/tuono_lib/src/server.rs, crates/tuono_lib/src/services/logger.rs, crates/tuono_lib/src/ssr.rs, crates/tuono_lib/src/vite_websocket_proxy.rs, crates/tuono_lib/tests/server_test.rs, crates/tuono_lib/tests/utils/health_check.rs, crates/tuono_lib/tests/utils/mock_server.rs, crates/tuono_lib_macros/Cargo.toml, crates/tuono_lib_macros/src/api.rs, crates/tuono_lib_macros/src/handler.rs, crates/tuono_lib_macros/src/utils.rs
=> chore: update cargo edition to 2024

examples/tuono-app/Cargo.toml, examples/tuono-tutorial/Cargo.toml, examples/with-mdx/Cargo.toml, examples/with-tailwind/Cargo.toml
=> chore: update examples rust edition

crates/tuono/src/commands/dev.rs, crates/tuono/src/source_builder.rs
Fixes None
Second chunk of improvements for the `Source builder` struct
=> refactor: `SourceBuilder`

crates/tuono/Cargo.toml, crates/tuono_internal/Cargo.toml, crates/tuono_lib/Cargo.toml, crates/tuono_lib_macros/Cargo.toml, packages/tuono-fs-router-vite-plugin/package.json, packages/tuono-router/package.json, packages/tuono/package.json
=> chore: bump version (v0.19.1)

package.json
- Fixes #624
- ~~(Maybe)~~ supersedes #680
=> test(e2e): run tests on Windows jobs

crates/tuono/Cargo.toml, crates/tuono/src/commands/dev.rs, crates/tuono/src/lib.rs, crates/tuono/src/process_manager.rs
Fixes #469
This PR refactors the `tuono dev` to support the automatic typescript's types generation. As collateral this also fixes #469
=> refactor: tuono dev script

.github/workflows/e2e-ci.yml, .github/workflows/repo-root-ci.yml, .github/workflows/rust-ci.yml, .github/workflows/typescript-ci.yml
=> ci: simplify CI OK jobs

packages/tuono/src/build/types.ts, packages/tuono/src/config/index.ts, packages/tuono/src/config/types.ts
=> refactor: create more types to simplify `TuonoConfig` management

examples/tuono-app/src/routes/__layout.tsx, examples/tuono-tutorial/src/routes/__layout.tsx, examples/with-mdx/src/routes/__layout.tsx, examples/with-tailwind/src/routes/__layout.tsx, packages/tuono/src/index.ts, packages/tuono/src/types.ts
=> feat: add `TuonoLayoutProps` interface

crates/tuono/Cargo.toml, crates/tuono_internal/Cargo.toml, crates/tuono_lib/Cargo.toml, crates/tuono_lib_macros/Cargo.toml, packages/tuono-fs-router-vite-plugin/package.json, packages/tuono-router/package.json, packages/tuono/package.json
=> chore: bump version (v0.19.2)

crates/tuono/src/commands/dev.rs, crates/tuono/src/source_builder.rs, crates/tuono/src/typescript/types_jar.rs
=> feat: refresh types on file change

packages/tuono/src/shared/DevResources.tsx, packages/tuono/src/shared/ProdResources.tsx, packages/tuono/src/shared/TuonoScripts.tsx, packages/tuono/src/types.ts
=> refactor: refine ServerPayload type using a union with mode as discriminant

crates/tuono/src/commands/dev.rs, crates/tuono/src/source_builder.rs, crates/tuono/src/typescript/types_jar.rs
=> feat: remove types on file delete

crates/tuono/src/typescript/file_types.rs, crates/tuono/src/typescript/types_jar.rs
=> feat: prevent duplicated types

crates/tuono/Cargo.toml, crates/tuono/src/commands/dev.rs, crates/tuono/src/process_manager.rs, crates/tuono/templates/server.rs, crates/tuono_internal/src/lib.rs, crates/tuono_internal/src/tuono_println.rs, crates/tuono_lib/src/server.rs
=> fix: prevent multiple server address print

package.json
Fixes None
Fixing a command typo
=> fix: format:fix turbo command

pnpm-lock.yaml
=> chore: dedupe dependencies

crates/tuono/Cargo.toml, crates/tuono_internal/Cargo.toml, crates/tuono_lib/Cargo.toml, crates/tuono_lib_macros/Cargo.toml, packages/tuono-fs-router-vite-plugin/package.json, packages/tuono-router/package.json, packages/tuono/package.json
=> chore: bump version (v0.19.3)

crates/tuono/src/commands/dev.rs, crates/tuono/src/source_builder.rs, crates/tuono/src/typescript/types_jar.rs, examples/tuono-tutorial/src/routes/pokemons/[pokemon].rs
=> feat: prevent file generation if type not changed

crates/tuono/src/typescript/file_types.rs, crates/tuono/src/typescript/parser/mod.rs, crates/tuono/src/typescript/parser/parse_enum.rs, crates/tuono/src/typescript/parser/parse_struct.rs, crates/tuono/src/typescript/parser/utils.rs, crates/tuono/src/typescript/utils.rs, examples/tuono-app/src/routes/index.rs, examples/tuono-tutorial/src/routes/index.rs, examples/tuono-tutorial/src/routes/pokemons/[pokemon].rs
=> feat: create base enum parser

crates/tuono/Cargo.toml, crates/tuono_internal/Cargo.toml, crates/tuono_lib/Cargo.toml, crates/tuono_lib_macros/Cargo.toml, packages/tuono-fs-router-vite-plugin/package.json, packages/tuono-router/package.json, packages/tuono/package.json
=> chore: bump version (v0.19.4)

examples/with-tailwind/src/styles/global.css
=> fix: tailwindcss template

crates/tuono_lib/Cargo.toml
Fixes None
The latest `ssr_rs` version adds supports for the Ii18n feature
=> chore: bump ssr_rs (0.8.3)

packages/tuono-react-vite-plugin/src/fs-routing/generator.ts, packages/tuono-react-vite-plugin/src/plugin.ts, packages/tuono-react-vite-plugin/src/styles.ts, packages/tuono-react-vite-plugin/tests/generator/catch_all/routeTree.expected.ts, packages/tuono-react-vite-plugin/tests/generator/mdx/routeTree.expected.ts, packages/tuono-react-vite-plugin/tests/generator/multi-level-root-dynamic/routeTree.expected.ts, packages/tuono-react-vite-plugin/tests/generator/multi-level/routeTree.expected.ts, packages/tuono-react-vite-plugin/tests/generator/single-level/routeTree.expected.ts, packages/tuono-router/src/components/CriticalCss.tsx, packages/tuono-router/src/components/NotFound.tsx, packages/tuono-router/src/components/RouteMatch.tsx, packages/tuono-router/src/route.ts
Fixes None
Two were the problems with the initial iteration of the CriticalCss generation:
- nested `__layout.tsx` files were not included
- css defined in `node_modules` were triggering an error
=> fix: improve critical css generation

crates/tuono/Cargo.toml, crates/tuono_internal/Cargo.toml, crates/tuono_lib/Cargo.toml, crates/tuono_lib_macros/Cargo.toml, packages/tuono-react-vite-plugin/package.json, packages/tuono-router/package.json, packages/tuono/package.json
=> chore: bump version (0.19.6)

crates/tuono_lib/src/manifest.rs
Fixes None
With this PR we improve the collection of the manifest data. Specifically it:
- correctly cleans the `.mdx` route paths
- collects also the CSS from the layout files
=> feat: improve manifest data collection

crates/tuono/Cargo.toml, crates/tuono_internal/Cargo.toml, crates/tuono_lib/Cargo.toml, crates/tuono_lib_macros/Cargo.toml, packages/tuono-react-vite-plugin/package.json, packages/tuono-router/package.json, packages/tuono/package.json
=> chore: bump version (v0.19.7)

crates/tuono/src/app.rs, crates/tuono/src/commands/new.rs, crates/tuono/src/process_manager.rs, crates/tuono/src/route.rs, crates/tuono/src/typescript/parser/parse_enum.rs, crates/tuono/tests/cli_build.rs, crates/tuono/tests/utils/mock_github_endpoint.rs, crates/tuono_internal/tests/utils.rs, crates/tuono_lib/src/env.rs, crates/tuono_lib/src/payload.rs, crates/tuono_lib/src/vite_reverse_proxy.rs, crates/tuono_lib_macros/src/api.rs
=> fix: lifetime notation

pnpm-lock.yaml
=> chore: dedupe upgraded dependencies
