tuono-labs/tuono

crates/tuono/Cargo.toml, crates/tuono/src/source_builder.rs, crates/tuono_lib/Cargo.toml, crates/tuono_lib/src/catch_all.rs, crates/tuono_lib/src/lib.rs, crates/tuono_lib/src/payload.rs, crates/tuono_lib/src/server.rs, crates/tuono_lib/src/ssr.rs, crates/tuono_lib_macros/Cargo.toml, crates/tuono_lib_macros/src/handler.rs, examples/tuono/Cargo.toml, examples/tutorial/Cargo.toml, packages/lazy-fn-vite-plugin/package.json, packages/tuono/package.json
The server was getting too complex to be handled by code generator side. 
Generating the server code using strings is complex and error prone for multilpe reasons.
Handling the server code directly within the `tuono_lib` create will help the project by:
- Easing the development
- Allowing the final projects to import just tuono_lib for what concerns the server management
- Allowing the final project to keep all the server related libs on sync
=> Refactor server 

crates/tuono/Cargo.toml, crates/tuono_lib/Cargo.toml, crates/tuono_lib/src/catch_all.rs, crates/tuono_lib/src/payload.rs, crates/tuono_lib/src/request.rs, crates/tuono_lib_macros/Cargo.toml, crates/tuono_lib_macros/src/handler.rs, docs/tutorial.md, examples/tuono/Cargo.toml, examples/tuono/src/routes/index.rs, examples/tutorial/src/routes/index.rs, examples/tutorial/src/routes/pokemons/GOAT.rs, examples/tutorial/src/routes/pokemons/[pokemon].rs, packages/fs-router-vite-plugin/package.json, packages/lazy-fn-vite-plugin/package.json, packages/tuono/package.json
This PR is a little improvement on the public API. 
```diff
-- pub async fn custom_handler(req: Request<'_>) ...
++ pub async fn custom_handler(req: Request) ...
```
=> Remove lifetime notation on Request

crates/tuono/Cargo.toml, crates/tuono_lib/Cargo.toml, crates/tuono_lib/src/manifest.rs, crates/tuono_lib_macros/Cargo.toml, docs/tutorial.md, examples/tutorial/src/routes/index.tsx, examples/tutorial/src/routes/pokemons/[pokemon].tsx, package.json, packages/fs-router-vite-plugin/package.json, packages/lazy-fn-vite-plugin/package.json, packages/tuono/package.json, packages/tuono/src/index.ts, packages/tuono/src/react-meta-tags.d.ts, packages/tuono/src/ssr/index.tsx
This PR adds the support for handling the meta tags by exposing the `<Head />` component to render on both - client and server - the meta tags in the HTML `<head>`.
For this first iteration I opt to use [react-meta-tags](https://github.com/s-yadav/react-meta-tags) which already implements a good set of utilities to handle the meta tags on the bundles for both the environments.
=> Add support for meta tags

crates/tuono/Cargo.toml, crates/tuono/src/app.rs, crates/tuono/src/cli.rs, crates/tuono/src/route.rs, crates/tuono/src/source_builder.rs, crates/tuono_lib/Cargo.toml, crates/tuono_lib_macros/Cargo.toml, packages/fs-router-vite-plugin/package.json, packages/lazy-fn-vite-plugin/package.json, packages/tuono/package.json, packages/tuono/src/router/hooks/useServerSideProps.tsx
This PR implements the SGG build option (`tuono build --static`). This in order to allow the development of websites that don't require any dynamic server capability.
This is the first iteration. The feature will be refined while working on the tuono documentation website trying to address real world deployment issues.
The step taken by the tuono source builder to statically generate the website are:
1. Build the source with vite
2. Clone the output assets into the `out/static` folder
3. Run the prod server on port 3000
4. Call any existing route and save it in a [file].html file (if require server data it also saves `__tuono/data/[file]/data.json` file)
=> Support Static Site Generation (SSG)

crates/tuono/src/app.rs, crates/tuono/src/cli.rs, crates/tuono/src/route.rs, crates/tuono_lib/src/response.rs
To better support custom file generation (like `sitemap.xml`) the `Response` enum has now the new `Response::Custom` variant to return the defined file.
The build script has been updated as well to support the static generation (SGG) of such files.
=> Add custom response type

apps/documentation/src/routes/documentation/tutorial/api-fetching.mdx, apps/documentation/src/routes/documentation/tutorial/redirections.mdx, crates/tuono/Cargo.toml, crates/tuono_lib/Cargo.toml, crates/tuono_lib_macros/Cargo.toml, crates/tuono_lib_macros/src/handler.rs, examples/tuono/src/routes/index.rs, examples/tutorial/src/routes/pokemons/GOAT.rs, packages/fs-router-vite-plugin/package.json, packages/lazy-fn-vite-plugin/package.json, packages/router/package.json, packages/tuono/package.json
This PR makes the `(2nd, ...)` handlers arguments optional.
Prev:
```
#[tuono_lib::handler]
async fn redirect_to_goat(_req: Request, _fetch: Client) -> Response {
...
}
```
After:
Prev:
```
#[tuono_lib::handler]
async fn redirect_to_goat(_req: Request) -> Response {
...
}
```
=> Make handler arguments optional

CONTRIBUTING.md
Minor followup to #85. Change `CONTRIBUTING.md` new issue links to point to the issue template chooser.
Unless otherwise user will land into a blank issue page.
=> docs(CONTRIBUTING): new link issue point to issue template chooser

crates/tuono/Cargo.toml, crates/tuono_lib/Cargo.toml, crates/tuono_lib/src/catch_all.rs, crates/tuono_lib/src/lib.rs, crates/tuono_lib/src/response.rs, crates/tuono_lib/src/server.rs, crates/tuono_lib/src/services.rs, crates/tuono_lib/src/services/logger.rs, crates/tuono_lib_macros/Cargo.toml, packages/fs-router-vite-plugin/package.json, packages/lazy-fn-vite-plugin/package.json, packages/router/package.json, packages/tuono/package.json
This PR is the first step about improving the current server setup by leveraging [tower](https://github.com/tower-rs/tower)'s services. 
> These changes will eventually enable tuono to leverage a plugin system for developing custom libraries on top of tower.
Here specifically I created a logger services that exactly matches the output of the previous logger. Since this is a service (so it wraps the whole HTTP request) the logger takes into account the whole request timing rather than just the time spent by tuono to execute the server side rendering.
> Note: right now it logs all the user defined endpoint requests (vite and catch_all excluded). This means that the client side routing API endpoints are logged (which I think they shouldn't). The next PR will update the routing system so I'll …
=> Create logger service

crates/tuono/src/app.rs, crates/tuono/src/route.rs
I got this exception when trying to use a hyphen in route. e.g. 
```
src/routes/openid-conntect/index.rs
```
assuming the fix it to replacing `-` to `_` that makes compiler happy.
=> fix: handle hyphen in route

apps/documentation/src/components/sidebar/sidebar.tsx, packages/router/src/router.ts, packages/router/src/types.ts
Few types change related to [ReactNode vs JSX.Element Discord thread](https://discord.com/channels/1307411506735874208/1307729152417337364)
=> refactor: replace () => JSX.Element with `React.ComponentType`

crates/tuono/Cargo.toml, crates/tuono/src/watch.rs
Related to Issue #34 
Previously updating watchexec to v5 leads to this error:
```
error[E0308]: mismatched types
--> crates/tuono/src/watch.rs:90:46
|
90 |         if action.signals().any(|sig| sig == Signal::Interrupt) {
|                                       ---    ^^^^^^^^^^^^^^^^^ expected `watchexec_supervisor::Signal`, found `watchexec_signals::Signal`
```
This PR fixes the import issue by changing `use watchexec-signals::Signal` to `use watchexec_supervisor::Signal`.
It also updates watchexec-signals to v4 with no further errors.
=> Update watchexec to v5 and watchexec-signals to v4

crates/tuono/src/scaffold_project.rs
This PR improves error handling for two cases:
- When attempting to overwrite an existing folder with `tuono new [existing_dir]`
- When attempting to use `tuono new` template flag with a non-existent template
=> Better error handling when trying to overwrite an existing folder and using a non-existent template

apps/documentation/src/components/sidebar/sidebar.tsx, apps/documentation/src/routes/documentation/contributing/index.mdx, apps/documentation/src/routes/documentation/contributing/local-development.mdx
Close #91.
<details>
<summary>Page preview</summary>
</details>
if you find the page too long, we could consider to split it into 3 different pages:
- setup
- development
- documentation
=> docs(CONTRIBUTING): add “Local development”

.github/workflows/ci-documentation.yml, .github/workflows/deploy-documentation.yml, .github/workflows/release.yml, .github/workflows/repo-root-ci.yml, .github/workflows/rust.yml, .github/workflows/typescript.yml
`push` should trigger CI only when performed on  `main` branch
> [!NOTE] 
> CI is still executed on every push on a branch with an opened PR.
> (The PR target can be any branch)
=> ci: trigger workflow only on `push` only on `main`

.github/workflows/rust.yml
On  `rust` CI remove `nightly` and `beta` toolchains from `windows` and `macOS`
=> ci(rust): avoid `beta` and `nightly` toolchains to be executed on macos and windows

crates/tuono/src/cli.rs, crates/tuono/src/source_builder.rs
In order to ease the testing suite development - that in the rust side doesn't need to build the react related modules - we add with this PR the new `--no-js-emit` flag to the `tuono build` command in order to just build the rust assets
=> feat: add --no-js-emit flag to tuono build command

.github/workflows/ci-documentation.yml, .github/workflows/deploy-documentation.yml, .github/workflows/repo-root-ci.yml, .github/workflows/rust.yml, .github/workflows/spell-checking.yml, .github/workflows/typescript.yml
Related to #185
When changing one or more of the following files
- `package.json`
- `pnpm-lock.yaml`
- `eslint.config.js`
- `tsconfig.json`
- `turbo.json`
- `.nvrc`
both `typescript.yml` and `ci-documentation.yml` should be triggered
----
> [!WARNING]
> Let me know if something similar should be done for `rust.yml`
----
> [!TIP]
> [I have performed a few tests in this example repository](https://github.com/marcalexiei/gitbub-actions-workflow-trigger-playground)
=> chore(github actions): refine `on` paths

Cargo.toml, crates/tuono/src/cli.rs
Related to rust 1.83.
You can see the error in this [GitHub action run](https://github.com/tuono-labs/tuono/actions/runs/12184578547/job/33988795069?pr=198).
----
Aiddtionaly I used the `format` function to improve server url creation using `TUONO_PORT` constant when building the site using `--static` flag
=> refactor(crates/tuono): build - ssg - disable `zombie_processes` warning and use `TUONO_PORT` to generate server URL

crates/tuono_lib_macros/Cargo.toml
When running `rust` related commands (e.g.: `cargo build`) I got the following warnings: 
```text
warning: /Users/marcalexiei/development/tuono/crates/tuono_lib_macros/Cargo.toml: `crate_type` is deprecated in favor of `crate-type` and will not work in the 2024 edition
(in the `tuono_lib_macros` library target)
warning: /Users/marcalexiei/development/tuono/crates/tuono_lib_macros/Cargo.toml: library `tuono_lib_macros` should only specify `proc-macro = true` instead of setting `crate-type`
warning: /Users/marcalexiei/development/tuono/crates/tuono_lib_macros/Cargo.toml: unused manifest key: lib.proc-marco
```
Using just `proc-macro = true` as suggested by warnings seems to remove all of them.
For reference, I'm using `rust` 1.83
=> fix(crates/tuono_lib_macros): remove Cargo.tml warnings

crates/tuono_lib/Cargo.toml, crates/tuono_lib/src/lib.rs, crates/tuono_lib/src/response.rs
This PR adds the support for reading and passing cookies to the HTTP response.
Passing cookies to the response is now possible by:
```rust
let mut props = Props::new(data);
props.add_cookie(Cookie::new());
return Response::Props(props);
```
The `Cookie` stuct has multiple implementation, so it is also possible to use different syntax like: `props.add_cookie(("name", "value"))`.
Also, `tuono_lib` re-export the `axum-extra::extractor::cookie` lib so that the end user can manage both `CookieJar` and `Cookie` structs
```rust
use tuono_lib::cookie::*;
```
Since the new support for cookies is now also possible to interact with the cookies passed from the `Request` like:
```rust
fn handler(req: Request) -> Response {
let cookies = CookieJar::from_headers(&req.headers);
}
```
This PR closes …
=> feat: add cookies to the response

eslint.config.js, packages/tuono/src/build/index.ts, packages/tuono/src/build/utils.spec.ts, packages/tuono/src/build/utils.ts
all content in any `build` folder in the project were excluded from `ESLint` processing.
E.g.: `packages/tuono/src/build`
This PR removes the exclusion and fix all error inside the above mentioned folder.
=> chore(eslint): remove `build` folder exclusion

apps/documentation/src/components/breadcrumbs/breadcrumbs.tsx, apps/documentation/src/components/table-of-content/get-headings.ts, apps/documentation/src/components/table-of-content/table-of-content.tsx, eslint.config.js, examples/tuono-tutorial/src/components/PokemonView.tsx, examples/tuono-tutorial/src/routes/index.tsx, packages/fs-router-vite-plugin/src/build-route-config.ts, packages/fs-router-vite-plugin/src/generator.ts, packages/fs-router-vite-plugin/src/has-parent-route.ts, packages/fs-router-vite-plugin/src/sort-route-nodes.ts, packages/fs-router-vite-plugin/src/types.ts, packages/fs-router-vite-plugin/src/utils.ts, packages/router/src/components/RouteMatch.tsx, packages/router/src/hooks/useRoute.tsx, packages/router/src/hooks/useRouterStore.tsx, packages/router/src/route.ts, packages/router/src/router.ts, packages/router/src/utils.ts, packages/tuono/src/build/utils.ts, packages/tuono/src/ssr/index.tsx
Switch [`@typescript-eslint/array-type`](https://typescript-eslint.io/rules/array-type/) rule to `generic`.
```ts
type MyArray = string[]
// now should be
type MyArray = Array<string>
```
A more detailed explanation can be found on the following blog post:
https://tkdodo.eu/blog/array-types-in-type-script
=> refactor(typescript): use generic instead of simple array type

apps/documentation/src/components/sidebar/config.ts
After https://github.com/tuono-labs/tuono/pull/196 merge, [`apps/documentation` do not pass CI](https://github.com/tuono-labs/tuono/actions/runs/12212363275/job/34070731153)
----
I also made a few refinements in sidebar item types.
=> refactor(apps/documentation): remove lint errors

apps/documentation/src/components/mdx-provider/mdx-code/mdx-code.tsx, apps/documentation/src/components/sidebar/config.ts, apps/documentation/src/routes/documentation/routing/link-and-navigation.mdx, spelling_global.txt
=> docs: add link and navigation page content

apps/documentation/package.json, examples/tuono-app/package.json, examples/tuono-tutorial/package.json, examples/with-mdx/package.json, examples/with-mdx/tuono.config.ts, package.json, packages/tuono/package.json, packages/tuono/src/build/index.ts, packages/tuono/src/build/utils.spec.ts, packages/tuono/src/build/utils.ts, packages/tuono/src/config/types.ts, pnpm-lock.yaml
Close #183.
Remove `mdx` related config from `tuono` npm package
---
(#212)
=> feat(packages/tuono): config – add `optimizeDeps` and `plugins` to `vite` options

packages/tuono/src/build/index.ts
Avoid js error involving `react` import when running `tuono dev`.
=> fix(packages/tuono): styles are not in the page when running `tuono dev`

apps/documentation/Cargo.toml, apps/documentation/package.json, apps/documentation/src/components/sidebar/config.ts, apps/documentation/src/routes/documentation/routing/dynamic-routes.mdx, apps/documentation/tuono.config.ts, pnpm-lock.yaml
=> docs: add dynamic routes page

packages/fs-router-vite-plugin/tests/generator.spec.ts, packages/lazy-fn-vite-plugin/src/index.ts, packages/lazy-fn-vite-plugin/src/utils.ts, packages/lazy-fn-vite-plugin/tests/sources/dynamic-only/client.expected.tsx, packages/lazy-fn-vite-plugin/tests/sources/dynamic-only/server.expected.tsx, packages/lazy-fn-vite-plugin/tests/sources/dynamic-only/source.tsx, packages/lazy-fn-vite-plugin/tests/transpileSource.test.ts
Fix issue 2 reported in https://github.com/tuono-labs/tuono/issues/216#issuecomment-2529385045
> unknown file: Cannot read properties of undefined (reading 'name') This error appear when dynamic is the only function exported by the tuono library import { dynamic } from 'tuono'. We need to improve the internal vite plugin + adding this test case
----
To fix the issue I replaced all casting inside `turnLazyIntoStatic` with helper function from `@babel/types` that provide check the correct node runtime and provide types accordingly. 
E.g.:
```tsx
isCallExpression(node: Node | null | undefined, opts?: Opts<CallExpression> | null): node is CallExpression;
```
I also refactored types by giving them name to reference `babel` or `vite` to avoid any confusion.
=> fix(packages/lazy-fn-vite-plugin): make `dynamic` function detection stricter

crates/tuono/src/source_builder.rs, crates/tuono/tests/cli_tests.rs, crates/tuono_lib_macros/src/handler.rs
change `tuono_lib::handlers` macro the name `route` to `tuono__internal__route` and `api` to `tuono__internal__api` to avoid naming collisions
Close https://github.com/tuono-labs/tuono/issues/186
=> feat: update tuono macro handler naming to avoid naming collisions

crates/tuono/src/route.rs, crates/tuono/tests/cli_tests.rs
close https://github.com/tuono-labs/tuono/issues/226
replace double underscore with single underscore
=> fix: catch-all paths replace double underscore with single underscore

packages/tuono/package.json, packages/tuono/src/build/index.ts, packages/tuono/src/ssr/index.tsx, packages/tuono/src/ssr/utils.ts, pnpm-lock.yaml
This PR turns the kinda "deprecated" `renderToString` to the new `renderToReadableStream` solving the last issue related to https://github.com/tuono-labs/tuono/issues/216.
For this iteration, we just wait for the whole stream, and then we pass it to the rust server. In a next iteration, we will need to pass every stream's chunk to rust to start streaming the response to the client. This will leverage the async server side resources loading, enhancing the user experience.
=> feat: update rendering from `renderToString` to `renderToReadableStream`

.github/ISSUE_TEMPLATE/bug_report.yml
Simplify `bug_report` template.
- Tuono version
- OS
- Browser version
- Node version
- Rust version
- Crate version
- Node package manager version
This is a required field, and its value should be the output from running
```shell
npx envinfo --system --npmPackages 'tuono' --binaries --browsers`
```
Example:
```shell
System:
OS: macOS 15.2
CPU: (8) arm64 Apple M3
Memory: 101.11 MB / 16.00 GB
Shell: 5.9 - /bin/zsh
Binaries:
Node: 22.11.0 - ~/.nvm/versions/node/v22.11.0/bin/node
npm: 10.9.0 - ~/.nvm/versions/node/v22.11.0/bin/npm
pnpm: 9.12.3 - ~/.nvm/versions/node/v22.11.0/bin/pnpm
Browsers:
Chrome: 131.0.6778.205
Safari: 18.2
npmPackages:
tuono: 0.16.4 => 0.16.4
```
This is a required field, and its value should be the output from running
```shell
rustc --version && cargo --version && …
```
=> chore(bug_report): make system-info fields required and add CLI command to retrieve them

packages/tuono/src/ssr/polyfills/messageChannel.spec.ts, packages/tuono/src/ssr/polyfills/messageChannel.ts
Follow up of https://github.com/tuono-labs/tuono/pull/238#discussion_r1894305766
Use [`vi.fn`](https://vitest.dev/api/vi.html#vi-fn) in `packages/tuono/src/ssr/polyfills/messageChannel.spec.ts` instead of function and support variables to perform assertions.
=> test(packages/tuono): messageChannel - use `vi.fn`

packages/tuono-fs-router-vite-plugin/src/index.ts, packages/tuono-lazy-fn-vite-plugin/src/index.ts, packages/tuono-lazy-fn-vite-plugin/tests/transpileSource.test.ts, packages/tuono/src/build/index.ts
Close #234.
All vite plugins now have consistent names and they are made available via a named export.
=> feat(packages/vite-plugins): use named export and consistent names across plugins

crates/tuono/src/scaffold_project.rs
The command `tuono new` downloads a template by searching the git tag number(= local cli version = release version).
Close #231
=> feat(crates/tuono): tuono new - download template by cli version and git tag

apps/documentation/src/routes/documentation/contributing/local-development.mdx
Related to https://github.com/tuono-labs/tuono/pull/276#pullrequestreview-2526914077
Script in "Local development" where incorrectly using `turbo`. 
They should use `pnpm` (which run the relevant script using `turbo`)
=> docs(local-development): use `pnpm` instead of `turbo`

renovate.json
Having a single PR for each dependency might be a pain when we have to update.
Using [packageRules](https://docs.renovatebot.com/configuration-options/#packagerules)  should help mitigate this problem.
At the moment I only a group for `eslint` related packages. 
Do you have any idea for additional groups?
=> chore(renovate): setup a package rule for eslint

.github/workflows/ci-documentation.yml, .github/workflows/deploy-documentation.yml, apps/documentation/CONTRIBUTING.md, apps/documentation/Cargo.toml, apps/documentation/package.json, pnpm-lock.yaml
- update `tuono` version used by the documentation
- `zustand` is no longer a dependency
- add instructions on how to update tuono version in the doc
=> docs: update tuono to 0.16.9

.github/pull_request_template.md, .github/workflows/pr-title-checker.yml, CONTRIBUTING.md, apps/documentation/src/components/navigation-buttons/navigation-buttons.tsx, apps/documentation/src/components/sidebar/config.ts, apps/documentation/src/routes/documentation/contributing/local-development.mdx, apps/documentation/src/routes/documentation/contributing/pull-requests.mdx
Close #286
- add new workflow to check PR title correctness
- add new `/documentation/contributing/pull-requests` page with all relevant information
- `pull_request_template.md` and `CONRIBUTING.md` files has been updated accordingly
---
> [!TIP]
> If you need to perform test on the title, you can open a PR in the POC repo linked in the issue.
@Valerioageno before merging this PR you should update `main` branch ruleset by making "PR title checker" required before a PR is mergeable.
[Please refer to "Require status checks to pass" in the example POC repo](https://github.com/marcalexiei/github-actions-pr-title-checker-playground/rules/3152235?ref=refs%2Fheads%2Fmain):
> [!TIP]
> After you performed this a `Required` badge should appear in near the status check informing that it is required.
=> ci: add pr title check to enforce a consistent git history

.github/workflows/repo-root-ci.yml, apps/documentation/src/routes/documentation/contributing/local-development.mdx, docker/.dockerignore, docker/Dockerfile, docker/compose.yml
I have dockerized the repo to simplify local development on the source code (one environment to rule them all!). To determine which packages to install and their order, I relied on the ['local development' documentation](https://tuono.dev/documentation/contributing/local-development).
Everything has been isolated in a dedicated docker folder (to avoid adding extra configuration files at the root of the project).
Currently, packages such as `pnpm`, `turbo`, and `cargo` are properly installed, and tuono (seems) compiles correctly. I noticed that the Node version is currently managed via the `/.nvmrc` file. To streamline the build process (and centralize versioning) with Docker, I have transferred this version into the `docker/compose.yml` file.
Firstly, install docker and docker compose. …
=> chore: dockerization of the tuono repo!

package.json, pnpm-lock.yaml
Supersedes #300:
cherry pick of #300 commit + `pnpm dedupe`.
=> chore(deps): update dependency prettier to v3.4.2

apps/documentation/src/routes/documentation/hooks/use-router.mdx
See [this discord thread](https://discordapp.com/channels/1307411506735874208/1328297481343336469). This PR adds documentation for the `useRouter` hook, including an example, documentation for the returned router object, and all methods returned (so far only router.push).
I like to rebase and squash PRs into one commit because I think it keeps history cleaner, so it might be a bit messy until I do that :)
=> docs: Add useRouter Documentation

pnpm-lock.yaml
This reverts commit 91c0a9ec31fa5decfaf7a6bff262e1c6a694f503.
=> fix(deps): revert update dependency @babel/types to v7.26.5 

apps/documentation/src/components/mdx-provider/mdx-bold/mdx-bold.tsx, apps/documentation/src/components/sidebar/config.ts, apps/documentation/src/routes/documentation/configuration.mdx, apps/documentation/src/routes/documentation/contributing/local-development.mdx
Close #303
Fill [tuono.config.ts](https://tuono.dev/documentation/configuration) with `vite`  references.
=> docs(configuration): fill page content

packages/tuono/src/index.ts
=> chore: remove `RouterProvider` from `tuono` exports

apps/documentation/src/routes/documentation/configuration.mdx
Added types and vite documentation for each vite option.
> [!NOTE]
> `vite.optimizeDeps` doesn't have a type because it's very complex.
> Note that this option has a standalone page inside vite documentation. 
<details><summary>Page preview</summary>
<p>
</p>
</details>
=> docs(configuration): add types and reformat `vite` properties

renovate.json
Reduce `prConcurrentLimit` to 5 to avoid cluttering pull requests list with many automated PRs.
https://docs.renovatebot.com/configuration-options/#prconcurrentlimit
> This setting - if enabled - limits Renovate to a maximum of x concurrent PRs open at any time.
> This limit is enforced on a per-repository basis.
=> chore(renovate): change `prConcurrentLimit` to 5 (default 10) and schedule once per week

pnpm-lock.yaml
Fix broken documentation CI related to clashing of node types impacting react types.
> [!IMPORTANT]
> To mitigate this type of issue a `pnpm dedupe` command should be executed after merging renovate PR
=> chore: dedupe deps

packages/tuono-fs-router-vite-plugin/package.json, packages/tuono-router/package.json, packages/tuono/package.json, pnpm-lock.yaml
Superseds #400 
- adds `pnpm dedupe`
- update version range for `tuono` and `tuono-router` packages
=> fix(deps): update dependency vite to v5.4.12 [security]

.github/workflows/ci-documentation.yml, .github/workflows/deploy-documentation.yml
docs related workflows were still using `tuono@0.16.9` rust version.
1. How about adding a section inside contributing about docs maintenance?
2. We could throw an error if the js version is not aligned with the rust binary version when running `dev` and `build` commands. 
[There is already a task on the v1 project ](https://github.com/orgs/tuono-labs/projects/2/views/1?pane=issue&itemId=89204577).
Maybe we could convert the project item into an issue so is more visible and maybe someone who want to tackle with the rust part could take care of it?
WDYT?
=> ci(docs): use tuono 0.17.3 in docs workflows

packages/tuono/src/build/config/create-json-config.spec.ts, packages/tuono/src/build/config/create-json-config.ts
Close #414.
The error was caused by the serialisation via structuredClone of a configuration containing a vite plugin.
More info can be found on `packages/tuono/src/build/config/create-json-config.ts`
Relevant unit tests were added to avoid regression.
=> fix(packages/tuono): build error when config contains vite plugins

crates/tuono/src/cli.rs, crates/tuono/tests/cli_build.rs, crates/tuono/tests/utils.rs
=> fix: check if project contains `tuono.config.ts` before running dev/build

apps/documentation/src/routes/documentation/tutorial/api-fetching.mdx
As per description, a snippet inside tutorial/api-fetching has some invalid code:
each list item wasn't wrapped around a `</li />` element
=> docs(tutorial): correct api fetching example

apps/documentation/src/routes/documentation/configuration.mdx, packages/tuono/src/config/types.ts
=> docs(configuration): add documentation for `server` option

crates/tuono_lib/src/server.rs
Fixes #460
- restore protocol at the beginning of server ready message
- renamed `server_http_address` removing the `http` since it's actually a hostname + port and doesn't have a protocol
(this is out of scope, but IMHO it's a nice to have, let me know if I need to revert it)
=> fix(crates/tuono_lib): print server url as valid URL to be clickable on CLI

.github/workflows/documentation-ci.yml, .github/workflows/documentation-deploy.yml
None
Retrieve tuono version to use when running CI reducing efforts when updating documentation version.
The used command is the following
```sh
pnpm ls tuono --filter=documentation | grep "tuono " | sed -E 's/.* ([0-9]+\.[0-9]+\.[0-9]+).*/\1/'
```
```sh
pnpm ls --filter=documentation tuono
```
produces
```text
documentation@0.0.1 /[...]/tuono/apps/documentation (PRIVATE)
dependencies:
tuono 0.17.5
```
---
```sh
grep "tuono "
```
returns
```text
tuono 0.17.5
```
---
```sh
sed -E 's/.* ([0-9]+\.[0-9]+\.[0-9]+).*/\1/'
```
clean the previous string by outputting only the semantic version:
```text
0.17.5
```
=> ci: get documentation `tuono` version automatically

apps/documentation/src/routes/documentation/rendering/server-side-rendering.mdx
Fixes https://github.com/tuono-labs/tuono/issues/454
=> docs: add SSR page

packages/tuono-router/package.json, packages/tuono-router/src/components/RouteMatch.spec.tsx, packages/tuono-router/src/hooks/useRoute.spec.ts, pnpm-lock.yaml
Fixes None
- `packages/tuono-router/src/components/RouteMatch.spec.tsx`
- use snapshot to test produced router structure
- as side effect of using snapshot `@testing-library/jest-dom` can be removed
- `packages/tuono-router/src/hooks/useRoute.spec.ts`
- move module mocking at the beginning of the file
- create `useRouterContextMock` to allow each test to customise the hook return.
Might be useful in the future if we need to add more tests.
=> test(packages/tuono-router): refine unit tests

apps/documentation/src/components/EditPage/EditPage.tsx, apps/documentation/src/components/Sidebar/sidebarElements.ts, apps/documentation/src/routes/documentation/__layout.tsx, apps/documentation/src/routes/documentation/getting-started/installation.mdx, apps/documentation/src/routes/documentation/getting-started/setup-project.mdx
Pending
- #486
Fixes #479
Add `getting-started/setup-project`
---
Refine `EditPage` `Divider`  spacing to avoid it collapse on the page content
E.g.: Last element of the page is code snippet
<details><summary>Before</summary>
<p>
</p>
</details> 
<details><summary>After</summary>
<p>
</p>
</details>
=> docs: add getting-started/setup-project

apps/documentation/src/components/Sidebar/sidebarElements.ts, apps/documentation/src/routes/documentation/functions/dynamic.mdx
Fixes None
@jacobhq I refined a little bit the `dynamic` page:
- Added an `Overview` heading (I think no text should be without any heading)
- Moved the `dynamic` button under the `useRouter` since I think it is less important
cc. @marcalexiei
=> docs: refine dynamic page hierarchy

apps/documentation/src/routes/documentation/configuration.mdx, packages/tuono-fs-router-vite-plugin/package.json, packages/tuono-router/package.json, packages/tuono/package.json, packages/tuono/src/build/config/normalize-config.spec.ts, packages/tuono/src/build/config/normalize-config.ts, packages/tuono/src/build/index.ts, packages/tuono/src/config/types.ts, pnpm-lock.yaml
Fixes #504
Add CSS key to vite config.
=> feat: add css key to vite config

apps/documentation/src/components/MdxProvider/MdxLink/MdxLink.tsx, packages/tuono-router/src/components/Link.spec.tsx, packages/tuono-router/src/components/Link.tsx
Fixes #531
This PR makes the link fallback to default `a` behaviour when a modifier key is being pressed.
=> fix: update link component to allow modifier+click to properly work, and write tests

packages/tuono-router/src/components/Link.spec.tsx
Fixes https://github.com/tuono-labs/tuono/pull/534#discussion_r1948149717
=> test(packages/tuono-router): use screen instead of render matchers

crates/tuono/Cargo.toml, crates/tuono/src/watch.rs
Fixes #285
This PR adds a spinner when the `tuono dev` command starts waiting for the project to build.
> Note. This is just a quick fix. The dev mode will eventually become interactive
=> feat: add spinner to 'tuono dev'

packages/tuono-router/src/components/RouterContext.tsx, packages/tuono/package.json, packages/tuono/src/ssr/server.tsx, pnpm-lock.yaml
Fixes #257 
This PR adds the support for URLSearchParams on the server side to allow `useRouter().query` to work on the server side
=> feat: polyfill URLSearchParams on the server side

crates/tuono/Cargo.toml, crates/tuono/src/app.rs, crates/tuono/src/build.rs, crates/tuono/src/cli.rs, crates/tuono/src/route.rs
Fixes #563 
Overall improvement to the CLI logging system.
This PR also fixes a couple of issue related to the `--static` build. This logging system will help understand future compilation bugs.
```sh
RUST_LOG=trace (any tuono command)
```
This command will log all the event from Level `trace` to the most critical.
Note: all the `error` even will always be triggered.
For this feature I used this amazing crate -> https://docs.rs/tracing/latest/tracing/
=> feat: setup default tracing subscriber

packages/tuono/src/build/config/create-json-config.spec.ts
Fixes https://github.com/tuono-labs/tuono/pull/582#discussion_r1966796341
`writeFileSpy` should be cleared before each test.
=> test(packages/tuono): `create-json-config` test are not clearing `writeFileSpy` mock

examples/tuono-app/tsconfig.json, examples/tuono-tutorial/tsconfig.json, examples/with-mdx/tsconfig.json, examples/with-tailwind/tsconfig.json
Followup of https://github.com/tuono-labs/tuono/pull/584#discussion_r1966472221
All `tsconfig` examples files follow the structure provided in the [typescript tsconfig reference](https://www.typescriptlang.org/tsconfig/#references).
---
<details><summary>Resolved</summary>
<p>
**Additional consideration:**
We might consider to create a package with the default tuono typescript config.
Something like `@tuono/ts-config` or `tuono-ts-config`
If you agree, let me know and I'll create a new task so we can discuss this further in the future.
</p>
</details>
=> refactor(examples): uniform `tsconfig.json` files

crates/tuono/src/route.rs
Fixes None
Since the need of creating a `robot.txt` file in the documentation (https://github.com/tuono-labs/tuono-documentation/issues/28), we add here the filter of extensions that allow custom endpoints.
=> feat: allow custom route with `.txt` extension

packages/tuono-router/src/components/Link.spec.tsx, packages/tuono-router/src/components/Link.tsx, packages/tuono-router/src/hooks/useRouter.ts
Fixes https://github.com/tuono-labs/tuono/issues/537
This PR does the following:
- add `replace` method to the instance returned by `useRouter` hook
- slightly refactor inner `useRouter` types to avoid repetition with adding `replace` method
- add `replace` prop to `Link` component that replaces the state by calling router's now added `replace` method
Related docs will be added with https://github.com/tuono-labs/tuono-documentation/pull/30
=> feat(packages/tuono-router): add `replace` method to router and `replace` prop to `Link`

examples/tuono-tutorial/src/routes/index.tsx
Fixes #612
Use `pokemon.name` as key in the pokemon list page.
I also checked other improper usages of `key` prop in the repo, I haven't found any so far
=> fix(examples/tuono-tutorial): use pokemon name as key instead of index

packages/tuono-router/src/components/Link.spec.tsx, packages/tuono-router/src/components/NotFound.spec.tsx, packages/tuono-router/src/components/NotFound.tsx, packages/tuono-router/src/components/NotFoundDefaultContent.tsx, packages/tuono-router/src/components/RouteMatch.spec.tsx, packages/tuono-router/src/hooks/useRoute.spec.ts
Follow up of https://github.com/tuono-labs/tuono/pull/633#pullrequestreview-2669394172
- uniform comonent style title ("Test ComponentName Component" → "< ComponentName />") 
- `packages/tuono-router/src/components/Link.spec.tsx`
- add missing `cleanup` function 
- `packages/tuono-router/src/components/NotFound.spec.tsx`
- use `vi.mocked` instead of mock + `vi.hoised`
- mock components and hooks directly used by `NotFound.spec.tsx` 
- replaced snapshots checks with mock checks to ensure component is working correctly
- In order to have a consistent test system checks I created `NotFoundDefaultContent` instead of using snapshots or rtl checks
- `packages/tuono-router/src/components/RouteMatch.spec.tsx`
- simplify `createRouteComponent` function
- …
=> test(packages/tuono-router): improve test using mocks

packages/tuono-router/src/components/RouteMatch.spec.tsx, packages/tuono-router/src/components/RouteMatch.tsx
=> fix: prevent returning the previous route data on route transition

crates/tuono/Cargo.toml, crates/tuono/src/commands/dev.rs, crates/tuono_lib/src/vite_reverse_proxy.rs, packages/tuono-react-vite-plugin/src/plugin.ts, packages/tuono-react-vite-plugin/src/styles.ts, packages/tuono-react-vite-plugin/src/types.ts, packages/tuono-router/src/components/CriticalCss.tsx, packages/tuono-router/src/components/Matches.tsx, packages/tuono-router/src/components/NotFound.tsx, packages/tuono-router/src/components/RouteMatch.tsx, packages/tuono-router/src/components/RouterProvider.tsx, packages/tuono-router/src/hooks/useRoute.ts, packages/tuono-router/src/types.ts, packages/tuono/src/shared/DevResources.tsx, packages/tuono/src/shared/RouterContextProviderWrapper.tsx, packages/tuono/src/shared/TuonoEntryPoint.tsx, packages/tuono/src/ssr/types.ts, packages/tuono/src/types.ts
Fixes #759
This PR improves the DX by preloading all the critical CSS during development so that the developers won't see any flash of unstyled HTML content at every refresh.
It follows pretty much the same implementation as the [remix framework](https://github.com/remix-run/remix/blob/main/packages/remix-dev/vite/styles.ts) by creating a new endpoint in the vite dev server `/vite-server/tuono_internal__critical_css?componentId=${route.id}` that compiles the css on demand (vite takes care of caching and optimizations)
=> feat: load critical CSS on development

crates/tuono/src/app.rs, crates/tuono/src/route.rs, crates/tuono/tests/cli_build.rs
Ensure HTTP methods are processed in uppercase to prevent mismatches. Added tests to validate the handling of routes with mixed-case HTTP method annotations and confirmed correct generation of imports.
None
Discovered kind of a fun bug testing my other changes. You'd think a  `HashSet<Method>` would only store unique http methods, but for reasons I don't really understand - that isn't honored when you use `Method::from_str()`. The effect of this in tuono is that if you had macros defined for api with mixed case, e.g. `#[handler(GET)]` and `#[handler(get)]` it would work fine, except you get duplicate imports in the generated main. This case would hit anyone who used the lowercase notation in a bootstrapped project because the templated healthcheck api uses uppercase.
=> fix(crates/tuono): Fix HTTP method handling for mixed-case input

crates/tuono_lib/src/manifest.rs, crates/tuono_lib/src/payload.rs, crates/tuono_lib/src/server.rs
Fixes None
Production build lacks of a correct assets loading. 
For instance:
This PR fix the above issue and also improve the performances by format and parse the manifest on server load
=> feat: parse manifest on server start
